### PR TITLE
Fix memory leaks

### PR DESCRIPTION
**Pull request by FreddieChopin**
Fix memory leaks in `lfs_init()`, `lfs_format()` and `lfs_mount()`

### CODE REVIEW

**Comment by geky** [comment]
Good catch. Mind if I squash your commits?

**Comment by FreddieChopin** [comment]
> Good catch. Mind if I squash your commits?

It's your project (; If you prefer to have them squashed, then no problem with me (;

> Bikeshedding: Could I suggest the name "cleanup"?

Certainly! I was wondering about a good name myself, "cleanup" is indeed nicer (; I've modified the commits.

**Comment by geky** [comment]
Well, on GitHub it does end up changing _your_ branch when I do this, which is unfortunate. Thanks for this!

**Comment by FreddieChopin** [comment]
> Well, on GitHub it does end up changing your branch when I do this, which is unfortunate.

Ha - didn't know about that (; No problem anyway, if I would really like to keep them (no idea what for) I always have my local copy.

**Pull request merged**
