### PR TITLE
Added possibility to open multiple files with LFS_NO_MALLOC enabled

### PR DESCRIPTION
**Pull request by dpgeorge**
The `LFS_NO_MALLOC` option is very useful, because some systems have very particular memory allocation needs.  But enabled this option doesn't allow to have multiple files open at the same time.  This PR adds a quick fix for this by allowing to pass in the `file_buffer` directly to `lfs_file_open()`, so the latter doesn't need to call `lfs_malloc()`.

I don't expect this to be merged as-is because it breaks the existing API.  But a feature along these lines would be very useful because it gives full functionality of littlefs without the need for any `malloc()` or `free()` functions.

Alternatives to this PR would be:
- a new function, eg `lfs_file_open_using()` which accepts the 5th parameter added here
- allow to set the global `lfs->cfg->file_buffer` pointer before each call to `lfs_file_open()` so the latter could pick up a new buffer each time

( Background: we are looking to integrate littlefs in MicroPython: https://github.com/micropython/micropython/pull/3847 )

### CODE REVIEW

**Comment by dpgeorge** [comment]
I have rebased this PR on top of the latest master, with change in license.

**Comment by geky** [comment]
Hi @dpgeorge, thanks for the pr (and rebasing). I think you're right passing a buffer into open would be a better API.

Tossing ideas around, one idea to make this future compatible would be to take in a sort of config struct. Similar to the lfs_mount/lfs_format functions:
``` cpp
struct lfs_file_config {
    void *buffer;
};

int lfs_file_open(lfs_t *lfs, lfs_file_t *file,
        const char *path, int flags,
        const struct lfs_file_config *cfg);
```

This would let us add additional configuration to the config structure in the future without breaking compatibility or having to come up with additional function names. Thoughts?

**Comment by dpgeorge** [comment]
> one idea to make this future compatible would be to take in a sort of config struct.

It might be simpler to just add a config entry to the `lfs_file_t` struct, which the user can populate if needed.  Then there doesn't need to be any additional args to `lfs_file_open`.

Alternatively, a user could just set the existing `file->cache.buffer` entry manually before calling `lfs_file_open`, in which case the user's buffer would be used.  That also doesn't require adding any args to the function.

**Comment by geky** [comment]
> It might be simpler to just add a config entry to the lfs_file_t struct, which the user can populate if needed. Then there doesn't need to be any additional args to lfs_file_open.

Hmm, although wouldn't that no longer be backwards compatible since the config entry would need to be zeroed by users that don't want to use a buffer?

**Comment by geky** [comment]
Those are all good ideas.

I believe the main benefit of providing a separate config struct is that it makes it clear to the user what needs to be initialized and what doesn't. And additionally the config struct could be stored in 

How about we go the "lfs_file_open_ext" route and add an additional open function as `lfs_file_opencfg`? The simpler `lfs_file_open` function can still be there.

---

One thing I'm considering is the addition of custom attributes (https://github.com/ARMmbed/littlefs/pull/48). Introducing a config struct (or setting members of the file struct) would open up a good way to introduct custom attributes before file open:

``` c
struct my_file {
    lfs_file_t file;
    struct lfs_file_config cfg;
    struct lfs_attr attrs[2];
    uint32_t timestamp;
    uint16_t number;
};

struct my_file file;
file->attrs[0].type = MY_TYPE_TIMESTAMP;
file->attrs[0].size = sizeof(file->timestamp);
file->attrs[0].buffer = &file->timestamp;
file->attrs[1].type = MY_TYPE_NUMBER;
file->attrs[1].size = sizeof(file->number);
file->attrs[1].buffer = &file->number;
file->cfg.buffer = malloc(128);
file->cfg.attrs = &file->attrs;
file->cfg.attr_count = 2;

int err = lfs_file_opencfg(lfs, &file->file, "filename.txt", LFS_O_RDONLY, &file->cfg);
```

**Comment by dpgeorge** [comment]
> How about we go the "lfs_file_open_ext" route and add an additional open function as lfs_file_opencfg? The simpler lfs_file_open function can still be there.

That sounds good.

> I believe the main benefit of providing a separate config struct is that it makes it clear to the user what needs to be initialized and what doesn't.

To allow to add entries to the file config struct in a backwards-compatible way, I guess you'd require the user to always do `memset(&file->cfg, 0, sizeof(file->cfg))`, then populate the used entries, before calling `lfs_file_opencfg()`.

For `const` file configuration structs this would still work because (in C99 at least) you can use named initialisers and the remaining entries will be zero'd out, eg:
```c
static uint8_t my_file_buffer[128];
static const struct lfs_file_config my_file_cfg = {
    .file_buffer = my_file_buffer,
    // all other entries are 0 by default
};
```

> One thing I'm considering is the addition of custom attributes (#48). Introducing a config struct (or setting members of the file struct) would open up a good way to introduct custom attributes before file open

Also sounds good.  Although in your example above, if you open the file with `LFS_O_RDONLY` I assume it'll ignore the attributes in the file config, because it can't write to the file?

**Comment by geky** [comment]
@dpgeorge How does this look to you? I added the `lfs_file_opencfg` onto your pr.

One other question is if these config structs should be copied into the structures during format/mount/opencfg:
1. Copy
  - RAM only allocated for format/mount/opencfg call
  - Allows modifications by format/mount/opencfg
2. Reference by pointer
  - Allows storing config in ROM

I went with the second option for consistency with `lfs_mount`.

> Also sounds good. Although in your example above, if you open the file with LFS_O_RDONLY I assume it'll ignore the attributes in the file config, because it can't write to the file?

It could still read the attributes, though there wouldn't be much advantage over and explicit `lfs_getattr` call.

**Comment by dpgeorge** [comment]
> How does this look to you? I added the lfs_file_opencfg onto your pr.

Thanks, I see it.

> One other question is if these config structs should be copied into the structures during format/mount/opencfg:
> ...
> I went with the second option for consistency with lfs_mount.

That brings up an interesting point: for files there would be two kinds of configurations: global configuration options that are common to all files (like attributes), and local configuration options just for a file (like the cache buffer).  If these are put into the same struct then it would be a waste of memory to allocate a new one of these structs for each file, since all the global config would be common and could have gone in ROM.  To be explicit on this point: the `void *buffer` entry in `lfs_file_config` must be different for each file and so that requires a different instance of this struct for each file that you want open at the same time.  And then you must copy into each of these structs the common global file config values, which could be quite large.  Regardless of if these file config structs go in ROM or RAM it's still wasteful repeating this data.

Maybe the common, global file config (like configuration of attributes and their types) needs to go in the `lft_config` struct.  Then only per-file config goes in `lft_file_config`.

**Comment by geky** [comment]
You're right that any common configuration should go into the global struct.

But I attributes fall into this category. A part of the attribute structure is the buffer that contain's the attribute's data. This would be unique for each file.

There's also the minor point that you may want different attributes for different files, but I'm not sure that's important.

On the plus side, you only pay the cost for the attribute structures if you use custom attributes.

**Comment by geky** [comment]
Rebased due to conflict with master and added version bump to v1.5

Hi @dpgeorge, does this change look good to you? Since it's backwards compatible I think we can go ahead and merge it without any problems (just a minor version bump).

**Comment by dpgeorge** [comment]
Yes it looks good to me, thanks!  It does look backwards compatible.

**Comment by geky** [comment]
Thanks for the initial pr!

**Comment by dpgeorge** [comment]
No problem.  There's not much left of my initial code/commit, I don't know if it's worth keeping it around or not.

**Comment by geky** [comment]
Sure thing, here we go

**Comment by dpgeorge** [comment]
Ok, I'm happy with it.

**Comment by dpgeorge** [comment]
Thanks for the work to get this merged, it's much appreciated!  FYI here is the change I made to support this new `lfs_file_opencfg()` function: https://github.com/micropython/micropython/pull/3847/commits/4b6bbbd134d88588319bf783233d9f46f5134d76

**Pull request merged**
