### PR TITLE
Fix build with -Wundef

### PR DESCRIPTION
**Pull request by rojer**
Part of https://github.com/mongoose-os-libs/vfs-fs-lfs/issues/2

### CODE REVIEW

**Comment by geky** [comment]
Hmm, is there a reason for not putting Wundef in the normal build options?
https://github.com/ARMmbed/littlefs/blob/master/Makefile#L32

Thanks for creating a PR.

**Comment by geky** [comment]
Hi @rojer, thanks for creating a PR. This is a good idea.

Hmm, is there a reason for not putting Wundef in the normal build options?
https://github.com/ARMmbed/littlefs/blob/master/Makefile#L32

**Comment by rojer** [comment]
well, the idea is to prevent this from happening in the future.

**Comment by geky** [comment]
The Makefile is used directly in CI: https://github.com/ARMmbed/littlefs/blob/master/.travis.yml#L18

If we move -Wundef to the Makefile, that just means users will have the warning if they run the tests locally.

The only reason -Werror is special is because halting on warnings can be a pain when testing/debugging locally.

**Comment by rojer** [comment]
ok, sorry, i misunderstood. moved to Makefile.

**Pull request merged**
